apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: myapp
        image: quxia83/myapp:tag  # Placeholder tag
        ports:
        - containerPort: 80
